version: '3.8'

services:
  mysql:
    image: mysql
    container_name: nx-admin-mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    restart: always
    volumes:
      - './mysql_data/data:/var/lib/mysql'
      - './mysql_data/conf.d:/etc/mysql/conf.d'
    environment:
      MYSQL_ROOT_PASSWORD: root
